import type { Metadata } from "next";
import { Geist, Geist_Mono, Walter_Turncoat } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const walter = Walter_Turncoat({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-walter'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${walter.className}  antialiased`}
      >
        <Toaster />
        {children}
      </body>
    </html>
  );
}
